name: Direct Database Migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the migration on'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Execute migration
        run: ./prisma/deploy.sh
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          
      - name: Notify success
        run: echo "Migration completed successfully" 